openapi: 3.0.3
info:
  title: Product Catalog API
  description: 'The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. '
  contact:
    name: John Smith
    url: 'https://acme-pet-supplies.co.uk/docs'
    email: john.smith@acme-pet-supplies.co.uk
  version: '1.0'
servers:
  - url: 'https://api.acme-pet-supplies.co.uk'
paths:
  /v1/catalog/categories:
    get:
      operationId: listCategories
      summary: List all categories
      description: List all categories.
      parameters: []
      responses:
        '200':
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimitRemaining'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimitReset'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CategoriesResponse'
        '401':
          $ref: '#/components/responses/401Response'
        '403':
          $ref: '#/components/responses/403Response'
        '406':
          $ref: '#/components/responses/406Response'
        '415':
          $ref: '#/components/responses/415Response'
        '429':
          $ref: '#/components/responses/429Response'
        '500':
          $ref: '#/components/responses/500Response'
      deprecated: false
      tags:
        - Categories
  /v1/catalog/products:
    get:
      operationId: listProducts
      summary: List all products
      description: List all products.
      parameters:
        - $ref: '#/components/parameters/include'
        - $ref: '#/components/parameters/filterCategory'
      responses:
        '200':
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimitRemaining'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimitReset'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        '401':
          $ref: '#/components/responses/401Response'
        '403':
          $ref: '#/components/responses/403Response'
        '406':
          $ref: '#/components/responses/406Response'
        '415':
          $ref: '#/components/responses/415Response'
        '429':
          $ref: '#/components/responses/429Response'
        '500':
          $ref: '#/components/responses/500Response'
      deprecated: false
      tags:
        - Products
  '/v1/catalog/products/{id}':
    get:
      operationId: viewProduct
      summary: View a product's details
      description: View a product's details.
      parameters:
        - $ref: '#/components/parameters/productId'
      responses:
        '200':
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimitRemaining'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimitReset'
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/400Response'
        '401':
          $ref: '#/components/responses/401Response'
        '403':
          $ref: '#/components/responses/403Response'
        '404':
          $ref: '#/components/responses/404Response'
        '406':
          $ref: '#/components/responses/406Response'
        '415':
          $ref: '#/components/responses/415Response'
        '429':
          $ref: '#/components/responses/429Response'
        '500':
          $ref: '#/components/responses/500Response'
      deprecated: false
      tags:
        - Products
  '/v1/catalog/products/{id}/reviews':
    get:
      operationId: listProductReviews
      summary: List reviews
      description: List all reviews for a product.
      parameters:
        - $ref: '#/components/parameters/productId'
      responses:
        '200':
          description: OK
          headers:
            RateLimit-Limit:
              $ref: '#/components/headers/rateLimit'
            RateLimit-Remaining:
              $ref: '#/components/headers/rateLimitRemaining'
            RateLimit-Reset:
              $ref: '#/components/headers/rateLimitReset'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ReviewsResponse'
        '400':
          $ref: '#/components/responses/400Response'
        '401':
          $ref: '#/components/responses/401Response'
        '403':
          $ref: '#/components/responses/403Response'
        '406':
          $ref: '#/components/responses/406Response'
        '415':
          $ref: '#/components/responses/415Response'
        '429':
          $ref: '#/components/responses/429Response'
        '500':
          $ref: '#/components/responses/500Response'
      deprecated: false
      tags:
        - Reviews
components:
  parameters:
    filterCategory:
      name: filterCategory
      required: false
      in: query
      description: Filter by category ID.
      schema:
        type: string
        format: uuid
        example: 1e32231d-b8a1-4145-b539-820301c2af64
        maxLength: 40
    include:
      name: include
      in: query
      description: List of included related resources
      required: false
      schema:
        type: string
        example: category
        maxLength: 30
    productId:
      name: id
      in: path
      description: Product identifier
      required: true
      style: simple
      schema:
        type: string
        format: uuid
        example: d8ec6b7c-a5f9-16ac-76d0-7da97292c582
  schemas:
    Category:
      description: A product category.
      type: object
      properties:
        id:
          description: Identifier of the category.
          type: string
          format: uuid
          example: 1e32231d-b8a1-4145-b539-820301c2af64
        type:
          type: string
          example: category
          maxLength: 8
        attributes:
          type: object
          additionalProperties: false
          properties:
            name:
              description: Name of the product category.
              type: string
              example: Dogs
              maxLength: 20
              minLength: 0
        relationships:
          type: object
          additionalProperties: false
          properties:
            contains_products:
              type: object
              additionalProperties: false
              properties:
                link:
                  type: object
                  additionalProperties: false
                  properties:
                    related:
                      type: string
                      example: 'https://api.acme-pet-supplies.com/v1/catalog/products?fields[catgory]=1e32231d-b8a1-4145-b539-820301c2af64'
                      maxLength: 150
      additionalProperties: false
      required:
        - id
        - type
        - attributes
      title: Category
    Pagination:
      description: An object containing pagination   information
      type: object
      properties:
        self:
          description: Relative uri cursor pointing to the current page.
          type: string
          format: uri
          maxLength: 100
        first:
          description: Cursor to the first page.
          type: string
          format: uri
          maxLength: 100
        prev:
          description: Relative uri cursor to the previous page.
          type: string
          format: uri
          maxLength: 100
        next:
          description: Relative uri  cursor to the next page.
          type: string
          format: uri
          maxLength: 100
        last:
          description: Relative uri cursor to the last page.
          type: string
          format: uri
      additionalProperties: false
      required:
        - self
      title: Pagination
    CategoriesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          maxItems: 25
        links:
          allOf:
            - $ref: '#/components/schemas/Pagination'
            - example:
                self: 'https://api.acme-pet-supplies.com/v1/catalog/categories?cursor=bccf5512'
                first: 'https://api.acme-pet-supplies.com/v1/catalog/categories?cursor=fa0a11ec'
                prev: 'https://api.acme-pet-supplies.com/v1/catalog/categories?cursor=0242ac120'
                next: 'https://api.acme-pet-supplies.com/v1/catalog/categories?cursor=651b1f06'
                last: 'https://api.acme-pet-supplies.com/v1/catalog/categories?cursor=3a1893e2'
      additionalProperties: false
      required:
        - data
        - links
      title: CategoriesResponse
    Link:
      description: a structured representation of a URL
      type: object
      properties:
        href:
          type: string
          example: 'https://example.com/'
          maxLength: 200
        meta:
          type: object
          additionalProperties: false
      required:
        - href
      title: Link Object
    Error:
      description: 'A JSON:API-compliant error response. This object is inherited by the specific response type.'
      type: object
      properties:
        errors:
          description: An array of Error objects
          type: array
          items:
            description: 'A JSON:API-compliant error object.'
            type: object
            additionalProperties: false
            required:
              - status
              - title
            properties:
              id:
                description: a unique identifier for this particular occurrence of the problem
                type: string
                format: uuid
              links:
                description: a link to further details about this particular occurrence of the problem
                type: object
                properties:
                  about:
                    $ref: '#/components/schemas/Link'
              status:
                description: the HTTP status code applicable to this problem
                type: integer
              code:
                description: an application-specific error code
                type: string
                maxLength: 10
              title:
                description: 'a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization'
                type: string
                maxLength: 100
              detail:
                description: 'a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized'
                type: string
                maxLength: 150
              source:
                description: contains references to the source of the error
                type: object
                properties:
                  pointer:
                    description: 'a JSON Pointer [RFC6901] to the associated entity in the request document'
                    type: string
                    maxLength: 500
                  parameter:
                    description: indicates which URI query parameter caused the error
                    type: string
                    maxLength: 50
              meta:
                description: a JSON meta object with non-standard meta-information about the error
                type: object
                additionalProperties: false
          minItems: 1
      required:
        - errors
      title: Error Response
    Product:
      description: An item in Acme's pet supplies catalog.
      type: object
      properties:
        id:
          description: Identifier for the product.
          type: string
          example: dcd53ddb-8104-4e48-8cc0-5df1088c6113
        type:
          type: string
          example: product
          maxLength: 7
        attributes:
          type: object
          additionalProperties: false
          properties:
            name:
              description: Name of the product.
              type: string
              example: Acme Uber Dog Rope Toy
              maxLength: 50
              minLength: 1
            description:
              description: A description of the product.
              type: string
              example: 'Acme Uber Dog Rope Toy provides hours of fun for your dog. Great for bouncing, throwing and catching.'
              maxLength: 300
              minLength: 0
            price:
              description: Price of the product.
              type: number
              example: 100
              maximum: 1000000
              minimum: 0
            keywords:
              description: 'A colleciton of words that describe the product, used for searching for it.'
              type: array
              items:
                type: string
              maxItems: 20
              minItems: 0
              uniqueItems: true
            reviewRating:
              description: Average product review rating.
              type: integer
              format: int32
              example: 5
              maximum: 5
              minimum: 1
            numberOfReviews:
              description: Number of product reviews.
              type: integer
              format: int32
              example: 10
        relationships:
          type: object
          additionalProperties: false
          properties:
            in_categories:
              type: object
              additionalProperties: false
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: 1e32231d-b8a1-4145-b539-820301c2af64
                      type:
                        type: string
                        example: category
                        maxLength: 8
              uniqueItems: true
            has_reviews:
              type: object
              additionalProperties: false
              properties:
                links:
                  type: object
                  additionalProperties: false
                  properties:
                    related:
                      type: string
                      example: 'https://api.acme-pet-supplies.com/v1/catalog/products/dcd53ddb-8104-4e48-8cc0-5df1088c6113/reviews'
                      maxLength: 100
      additionalProperties: false
      required:
        - id
        - type
        - attributes
        - relationships
      title: Product
    ProductsResponse:
      type: object
      properties:
        data:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/Product'
          maxItems: 25
        included:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          uniqueItems: true
        links:
          allOf:
            - $ref: '#/components/schemas/Pagination'
            - example:
                self: 'https://api.acme-pet-supplies.com/v1/catalog/products?cursor=bccf5512'
                first: 'https://api.acme-pet-supplies.com/v1/catalog/products?cursor=fa0a11ec'
                prev: 'https://api.acme-pet-supplies.com/v1/catalog/products?cursor=0242ac120'
                next: 'https://api.acme-pet-supplies.com/v1/catalog/products?cursor=651b1f06'
                last: 'https://api.acme-pet-supplies.com/v1/catalog/products?cursor=3a1893e2'
      additionalProperties: false
      title: ProductsResponse
    Review:
      description: A review for a product.
      type: object
      properties:
        id:
          description: Identifier for a product review.
          type: string
          format: uuid
        type:
          type: string
          example: review
          maxLength: 6
        attributes:
          type: object
          additionalProperties: false
          properties:
            content:
              description: Review content.
              example: This dog toy is great! My dog loved to play with it. I thoroughly recommend.
              maxLength: 500
              minLength: 0
              type: string
            rating:
              description: 'The rating of the review. A number in the range 1 to 5, 1 for lowest and 5 for highest.'
              type: integer
              format: int32
              example: 5
              maximum: 5
              minimum: 1
            authorName:
              description: Name of the author of the review.
              type: string
              example: Jill Baker
              maxLength: 30
            submittedDate:
              description: Date the review was submitted.
              type: string
              format: date-time
              example: '2022-04-12T23:20:50.52Z'
          required:
            - content
            - rating
            - authorName
            - submittedDate
        relationships:
          type: object
          additionalProperties: false
          properties:
            for_product:
              type: object
              properties:
                links:
                  type: object
                  properties:
                    related:
                      type: string
                      format: uri
                      example: 'https://api.acme-pet-supplies.com/v1/catalog/products/dcd53ddb-8104-4e48-8cc0-5df1088c6113'
                      maxLength: 100
      required:
        - productReviewId
        - content
        - rating
        - authorName
        - submittedDate
        - productId
      title: Review
    ReviewsResponse:
      type: object
      properties:
        data:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/Review'
          maxItems: 25
        links:
          allOf:
            - $ref: '#/components/schemas/Pagination'
            - example:
                self: 'https://api.acme-pet-supplies.com/v1/catalog/reviews?cursor=bccf5512'
                first: 'https://api.acme-pet-supplies.com/v1/catalog/reviews?cursor=fa0a11ec'
                prev: 'https://api.acme-pet-supplies.com/v1/catalog/reviews?cursor=0242ac120'
                next: 'https://api.acme-pet-supplies.com/v1/catalog/reviews?cursor=651b1f06'
                last: 'https://api.acme-pet-supplies.com/v1/catalog/reviews?cursor=3a1893e2'
      additionalProperties: false
      required:
        - data
        - links
      title: ReviewsResponse
  headers:
    rateLimit:
      description: The quota units associated to the client in the current time-window.
      schema:
        type: integer
    rateLimitRemaining:
      description: Remaining quota units associated to the client.
      schema:
        type: integer
    rateLimitReset:
      description: Number of seconds until the quota resets.
      schema:
        type: integer
  responses:
    401Response:
      description: Not authorized
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Not authorized
                status: 401
                detail: Authentication failure.
                id: 8011c394-30c9-11ed-a261-0242ac120002
    403Response:
      description: Forbidden
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Forbidden
                status: 403
                detail: Access to this resource is forbidden. Please check you are authorized to access this resource.
                id: 747c7b00-30c9-11ed-a261-0242ac120002
    406Response:
      description: Not Acceptable
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Not Acceptable
                status: 406
                detail: 'Accept header contains the JSON:API media type and instances of that media type are modified with media type parameters.'
                id: 64ef46ea-30c9-11ed-a261-0242ac120002
    415Response:
      description: 415 Unsupported Media Type
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: 415 Unsupported Media Type
                status: 415
                detail: 'Request specifies the header Content-Type: application/vnd.api+json with media type parameters.'
                id: ef2692f4-3ca4-44d9-b70a-7cfd5d78d3a1
    429Response:
      description: 429 Too Many Requests
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
        Retry-After:
          description: 'If request limit exceeded, retry after this time window.'
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: 429 Too Many Requests
                status: 429
                detail: Too many requests. Request quota exceeded in time window. Try again soon
                id: ef2692f4-3ca4-44d9-b70a-7cfd5d78d3a1
    500Response:
      description: 500 Internal Server Error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: 500 Internal Server Error
                status: 500
                detail: Internal server error
                id: ef2692f4-3ca4-44d9-b70a-7cfd5d78d3a1
    400Response:
      description: Bad Request
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Bad Request
                status: 400
                detail: Bad request. Please check the request is valid.
                id: 8011c394-30c9-11ed-a261-0242ac120002
    404Response:
      description: Not Found
      headers:
        RateLimit-Limit:
          description: The quota units associated to the client in the current time-window.
          schema:
            type: integer
        RateLimit-Remaining:
          description: Remaining quota units associated to the client.
          schema:
            type: integer
        RateLimit-Reset:
          description: Number of seconds until the quota resets.
          schema:
            type: integer
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - title: Not Found
                status: 404
                detail: Resource not found.
                id: 6c4a6b54-30c9-11ed-a261-0242ac120002
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 'OAuth2 security scheme. JWTs follow RFC8725 recommendations. For more information, please see https://acme-pet-supplies.co.uk/docs/oauth'
      flows:
        authorizationCode:
          authorizationUrl: 'https://acme-pet-supplies.co.uk/oauth/authorize'
          tokenUrl: 'https://acme-pet-supplies.co.uk/oauth/token'
          scopes:
            read: Read catalog information
tags:
  - name: Categories
    description: A category is a class of products with common characteristics
  - name: Products
    description: A product is an item for sale on the store.
  - name: Reviews
    description: A review is a critical assessment of a product by a customer.
security:
  - OAuth2: []
